### ISSUE TITLE
Colorized margin

### ISSUE THREAD

**Issue by cod378** [dragnilar/Custom-Color-Themes#1]
Hi, please tell me how to made colorized code margin like your **"Dark Green Theme for Visual Studio 2022"** screenshot.
___

![Dark Green Theme for VS2022](https://github.com/dragnilar/Custom-Color-Themes/raw/master/Dark%20Green%20Theme%202022/screenshot.png)

Thanks for your help :)

**Comment by beeaify** [comment]
Hi! Did you find out?

**Comment by stephenjeffreywhite** [comment]
@codex78  @beeaify  My apologies, I didn't see this one. You can get that using the indent rainbow extension:

https://marketplace.visualstudio.com/items?itemName=chingucoding.IndentRainbow

**Comment by cod378** [comment]
> @codex78 @beeaify My apologies, I didn't see this one. You can get that using the indent rainbow extension:
> 
> https://marketplace.visualstudio.com/items?itemName=chingucoding.IndentRainbow

Tnaks :)
